server:
 port: 8008



spring:
 application:
   name: APIGATEWAY-SERVICE
   cloud:
   gateway:
   routes:
   - id:
   uri: http://localhost:8081/
   predicates:
   - Path=/customer/**
   - id:
 uri: http://localhost:8082/
 predicates:
 - Path=/washer/**