server:
  port: 9999

spring:
  application:
     name: APIGATWAY-SERVICE
  cloud:
    gateway:
      routes:
      - id: 
        uri: http://localhost:8081/
        predicates:
        - Path=/admin/**
      - id: 
        uri: http://localhost:8082/
        predicates:
        - Path=/customer/**
      - id: 
        uri: http://localhost:8083/
        predicates:
        - Path=/order/**
      - id: 
        uri: http://localhost:8085/
        predicates:
        - Path=/washer/**